---

language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

# Don't get too excited.  This is a free appid, the same that you can
# get for yourself at https://datamarket.azure.com

script: 
  mvn test -Dazureappid=V+SCgiHOXF9nUrgEhET3f2TaFV7Ba8jQv9CxdybrTmg=

